server:
  port: 7004
  servlet:
    context-path: /stock-order
spring:
  application:
    name: eureka-client-stock-order
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/stock_system?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Xhl7205019!
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: ImoocCouponHikariCP
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 10000
#    cluster:
#      nodes: "stock.redis.cache.windows.net:6379"
#    password: "Lfg82s6BwxKESKTzA4l07OLQRNi3rhBOKAzCaHaQr8A="

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
info:
  app:
    name: stock-order
    groupId: com.example.stock
    artifactId: stock-order
    version: 1.0-SNAPSHOT
logging:
  level:
    com.example.stock: debug
    logging:
      level:
        org:
          springframework:
            web:
              servlet:
                mvc:
                  method:
                    annotation=TRACE: null
