spring:
  application:
    name: stock-eureka

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8000/eureka,http://${eureka.instance.hostname}:8001/eureka
  server:
    enable-self-preservation: true
#    renewal-percent-threshold: 0.45